/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromiseRouteImport } from './routes/promise'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as ItalyRouteImport } from './routes/italy'
import { Route as FinalRouteImport } from './routes/final'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AffirmationsRouteImport } from './routes/affirmations'
import { Route as IndexRouteImport } from './routes/index'

const PromiseRoute = PromiseRouteImport.update({
  id: '/promise',
  path: '/promise',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ItalyRoute = ItalyRouteImport.update({
  id: '/italy',
  path: '/italy',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalRoute = FinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AffirmationsRoute = AffirmationsRouteImport.update({
  id: '/affirmations',
  path: '/affirmations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affirmations': typeof AffirmationsRoute
  '/favorites': typeof FavoritesRoute
  '/final': typeof FinalRoute
  '/italy': typeof ItalyRoute
  '/letter': typeof LetterRoute
  '/messages': typeof MessagesRoute
  '/promise': typeof PromiseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affirmations': typeof AffirmationsRoute
  '/favorites': typeof FavoritesRoute
  '/final': typeof FinalRoute
  '/italy': typeof ItalyRoute
  '/letter': typeof LetterRoute
  '/messages': typeof MessagesRoute
  '/promise': typeof PromiseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affirmations': typeof AffirmationsRoute
  '/favorites': typeof FavoritesRoute
  '/final': typeof FinalRoute
  '/italy': typeof ItalyRoute
  '/letter': typeof LetterRoute
  '/messages': typeof MessagesRoute
  '/promise': typeof PromiseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affirmations'
    | '/favorites'
    | '/final'
    | '/italy'
    | '/letter'
    | '/messages'
    | '/promise'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affirmations'
    | '/favorites'
    | '/final'
    | '/italy'
    | '/letter'
    | '/messages'
    | '/promise'
  id:
    | '__root__'
    | '/'
    | '/affirmations'
    | '/favorites'
    | '/final'
    | '/italy'
    | '/letter'
    | '/messages'
    | '/promise'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffirmationsRoute: typeof AffirmationsRoute
  FavoritesRoute: typeof FavoritesRoute
  FinalRoute: typeof FinalRoute
  ItalyRoute: typeof ItalyRoute
  LetterRoute: typeof LetterRoute
  MessagesRoute: typeof MessagesRoute
  PromiseRoute: typeof PromiseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promise': {
      id: '/promise'
      path: '/promise'
      fullPath: '/promise'
      preLoaderRoute: typeof PromiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/italy': {
      id: '/italy'
      path: '/italy'
      fullPath: '/italy'
      preLoaderRoute: typeof ItalyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final': {
      id: '/final'
      path: '/final'
      fullPath: '/final'
      preLoaderRoute: typeof FinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affirmations': {
      id: '/affirmations'
      path: '/affirmations'
      fullPath: '/affirmations'
      preLoaderRoute: typeof AffirmationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffirmationsRoute: AffirmationsRoute,
  FavoritesRoute: FavoritesRoute,
  FinalRoute: FinalRoute,
  ItalyRoute: ItalyRoute,
  LetterRoute: LetterRoute,
  MessagesRoute: MessagesRoute,
  PromiseRoute: PromiseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
